### ISSUE TITLE
討論是否有必要製作繁體中文版翻譯（及擴展包）

### ISSUE THREAD

**Issue by NaitLee** [NaitLee/xon-cn-ext#1]
（注：我習慣使用簡體技術術語）

近月來我逐漸意識到，在翻譯這件事上最好是寫傳統漢字。

[正如 RIME 所講](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E7%B0%A1%E5%8C%96%E5%AD%97%E8%BC%B8%E5%87%BA)，傳統漢字包含更多信息。於此，我們可以：

1. 對於每個要翻譯的文件，用傳統漢字寫一個源文件，（可選的）各詞彙之間（尤其是技術術語）用比如 ZWSP `U+200B ​` 分開
2. 用 [OpenCC](https://github.com/BYVoid/OpenCC) 轉換出簡體和正體版本，有必要時替換掉有差別的用詞（也去掉 ZWSP）
3. 這樣就兼顧了簡繁兩者；也不會在轉換上鬧笑話，又算是充分、合理利用了時間 😆

[Xonotic 遊戲本身](https://explore.transifex.com/team-xonotic/xonotic/)的繁體翻譯并不完善，而簡體卻近乎完成。咫尺天涯啊！我好想着手解決。
（這事還有一個問題：之前的翻譯貢獻者們會不會答應這樣的全盤替換 😜）

我覺得現在開始還不算晚 😃 大家可以說說有關想法。

**Comment by fahad15090** [comment]
很好，但是把两种语言都放在其他能够理解的地方

**Comment by NaitLee** [comment]
Oh, I think here is indeed the most reasonable place 🙃 as this repo is (at the moment) the only place with detailed & direct (unofficial) Chinese translation resource, hence people may search the Web then arrive here to get touched.

After that, the resources of both versions can be branched in one repo.
(So to switch language one just `git checkout zh-cn/zh-tw/...`)
(The idea of “extended translation pack” implies “only one can be used at once”)

(Alright here is truly a bit small, a forum should be better)
(But Xonotic official community is a little bit inactive)

**Comment by NaitLee** [comment]
The plan is done perfectly.

The infrastructure should be okay for official translation resource, too.
I’d look into how to achieve that, gracefully.
